let dados = [
    {
        imagem: "./images/programacao.svg",   
        titulo:"Programação",
        temNaAlura: "sim",
        temNaalua: "./images/certo.svg",
        programação: "sim",
        programaçãoC: "./images/erro.svg",
        formacoes: 58,
        diferencaForacoes: "./images/baixo.svg",        
        cursos: 258,
        diferencaCurso: "./images/baixo.svg",
        resultado: "Resposta errada",
    },
    {
        imagem: "./images/front-end.svg",
        titulo:"Front-End",
        temNaAlura: "sim",
        temNaalua: "./images/certo.svg",
        programação: "sim",
        programaçãoC: "./images/erro.svg",
        formacoes: 32,
        diferencaForacoes: "/images/cima.svg",
        cursos: 154,
        diferencaCurso: "/images/cima.svg",
        resultado: "Resposta errada",
    },
    {
        imagem: "./images/datascience.svg",
        titulo:"Data Science",
        temNaAlura: "sim",
        temNaalua: "./images/certo.svg",
        programação: "sim",
        programaçãoC: "./images/erro.svg",
        formacoes: 49,
        diferencaForacoes: "./images/baixo.svg",
        cursos: 292,
        diferencaCurso: "./images/baixo.svg",
        resultado: "Resposta errada",
    },
    {
        imagem: "./images/ia.svg",
        titulo: "Intelaigência Artificial",
        temNaAlura: "sim",
        temNaalua: "./images/certo.svg",
        programação: "sim",
        programaçãoC: "./images/erro.svg",
        formacoes: 70,
        diferencaForacoes: "/images/cima.svg",        
        cursos: 70,
        diferencaCurso: "/images/cima.svg",
        resultado: "Resposta errada",
    },
    {
        imagem: "./images/devops.svg",
        titulo:"Devops",
        temNaAlura: "sim",
        temNaalua: "./images/certo.svg",
        programação: "sim",
        programaçãoC: "./images/erro.svg",
        formacoes: 28,
        diferencaForacoes: "/images/cima.svg",
        cursos: 137,
        diferencaCurso: "/images/cima.svg",
        resultado: "Resposta errada",
    },
    {
        imagem: "./images/ux.svg",   
        titulo:"Ux & Design",
        temNaAlura: "sim",
        temNaalua: "./images/certo.svg",
        programação: "não",
        programaçãoC: "./images/certo.svg",
        formacoes: 45,
        diferencaForacoes: "./images/certo.svg",
        cursos: 205,
        diferencaCurso: "./images/certo.svg",
        resultado: "RESPOSTA CERTA",
    },
    {
        imagem: "./images/mobile.svg",
        titulo:"Mobile",
        temNaAlura: "sim",
        temNaalua: "./images/certo.svg",
        programação: "sim",
        programaçãoC: "./images/erro.svg",
        formacoes: 21,
        diferencaForacoes: "/images/cima.svg",
        cursos: 125,
        diferencaCurso: "/images/cima.svg",
        resultado: "resposta errada",
    },
    {
        imagem: "./images/inovacao.svg",
        titulo:"Inovação & Gestão",
        temNaAlura: "sim",
        temNaalua: "./images/certo.svg",
        programação: "não",
        programaçãoC: "./images/certo.svg",
        formacoes: 52,
        diferencaForacoes: "./images/baixo.svg",
        cursos: 305,
        diferencaCurso: "./images/baixo.svg",

        resultado: "Resposta errada",
    },

];
